name: kronos-dmz
services:
  dvwa_target:
    image: ghcr.io/digininja/dvwa:latest
    container_name: kronos_dvwa_dmz
    restart: unless-stopped
    ports:
      - "192.168.20.50:80:80"
    environment:
      DB_SERVER: db
      DB_DATABASE: dvwa
      DB_USER: dvwa
      DB_PASSWORD: ${DVWA_DB_PASSWORD:?External environment file required}
    depends_on:
      db:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    mem_limit: 512m
    cpus: 0.75
    pids_limit: 150
    logging:
      driver: json-file
      options: {max-size: "5m", max-file: "2"}
    networks: [dmz_net]
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: ${DVWA_DB_PASSWORD:?External environment file required}
      MYSQL_ROOT_PASSWORD: ${DVWA_DB_ROOT_PASSWORD:?External environment file required}
    volumes:
      - dvwa_db:/var/lib/mysql
    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      interval: 10s
      timeout: 5s
      retries: 12
    mem_limit: 512m
    logging:
      driver: json-file
      options: {max-size: "5m", max-file: "2"}
    networks: [dmz_net]
volumes:
  dvwa_db:
networks:
  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24
          gateway: 172.20.20.1
